spring.application.name=api

# Datasource PostgreSQL (Supabase) - Substitua URL, usuario e senha
spring.datasource.url=jdbc:postgresql://db.gwexoqubgpomuhufkqen.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Doceyncantos
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=doces
spring.jpa.show-sql=true

# JWT - TROCAR o secret antes de usar em producao
app.jwt.secret=TROQUE_ESTE_SECRET_POR_UM_VALOR_SEGURO_DE_NO_MINIMO_256_BITS
app.jwt.expiracao-minutos=60

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
